apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push
spec:
  params:
    - name: store
      type: string
      description: Store URL
    - name: outputPath
      type: string
      description: Output path of .tar.gz in store
    - name: image
      type: string
      description: Docker image name
    - name: version
      type: string
      description: Docker image version
  steps:
    - name: push
      image: dlip/push-nix-store-docker-image
      args:
        - "$(params.store)"
        - "$(params.outputPath)"
        - "$(params.image):$(params.version)"
