apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push
spec:
  steps:
    - name: push
      image: nixos/nix
      script: |
        #!/usr/bin/env sh
        echo "Hello from sh!"
        mkdir /etc/containers
        echo '{"default": [{"type": "insecureAcceptAnything"}], "transports": {"docker-daemon": {"": [{"type":"insecureAcceptAnything"}]}}}' > /etc/containers/policy.json
        nix-env -iA nixpkgs.nixUnstable nixpkgs.skopeo
        nix --experimental-features nix-command store cat --store http://nix-cache.home.lipscombe.com.au/ /nix/store/c9ik4y32qcgy1zk01wc7p7zgk1a9kpnz-envy.sh.tar.gz | skopeo copy docker-archive:/dev/stdin docker://dlip/envynix
