apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push
spec:
  params:
    - name: store
      type: string
      description: Store URL
    - name: outputPath
      type: string
      description: Output path of .tar.gz in store
    - name: image
      type: string
      description: Docker image name
    - name: version
      type: string
      description: Docker image version
  steps:
    - name: push
      image: nixos/nix
      script: |
        #!/usr/bin/env sh
        echo "Hello from sh!"
        mkdir /etc/containers
        echo '{"default": [{"type": "insecureAcceptAnything"}], "transports": {"docker-daemon": {"": [{"type":"insecureAcceptAnything"}]}}}' > /etc/containers/policy.json
        nix-env -iA nixpkgs.nixUnstable nixpkgs.skopeo
        nix --experimental-features nix-command store cat --store $(params.store) $(params.outputPath) | skopeo copy docker-archive:/dev/stdin docker://$(params.image):$(params.version)
