apiVersion: v1
kind: Secret
metadata:
    name: my-database-secret
    namespace: flux-system
stringData:
    database-password: ENC[AES256_GCM,data:OxbgTd8=,iv:MUJGehm4L/DP7RMugYkEcvGbgwuTMvTJvp4z07yNLao=,tag:jAwmbuW4Bg/MV0/ZGEDNag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-28T11:12:31Z"
    mac: ENC[AES256_GCM,data:xUvL7UdsJoErjO1uAigAktp13eoZbnXTWq1AODV6z+ItmBNK1vEzawgSJN3NpjjHmCOfSsa/Xc5PBwftzFevdKQ0H66QSUFn/rcM7OYyk3OGI9z9ctdNXATxXjFCa70EvR/cEaQgiM3u3KFEG3f/aOWhKVxx7dSeaxY+UHO0UEM=,iv:3zgAFxUQOw/0VYtPlxroniHfY79xuYfAqnskFIPb+QA=,tag:sdxy1GbfMtoT2FKieD7ASQ==,type:str]
    pgp:
        - created_at: "2021-05-28T11:12:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2B3sW1xNoFSAQ/7Bqj/CyJsQcpXpEJMMPXo/d3CptBwxEJz1z1VL7LQ5EEP
            B0MBazFUgUFfTPgGhgxYfAELUryUyUEe4SGmNGGSP2QOUHw/IweyjLRd9n3q4mvx
            DmuwKPD4aftLzNBwAeYts1m21GAYY3zZfX4gcQa0eNUm3YeFole4UR7Orj+vlRXm
            2n+tD7L20055CO3lA+DGDM03lx9NPE6yJybHGBgJl+SEb9N1mrfMuWbXNXoudI2i
            39EbqWv5NBZXtYBQMOM4WY17IJYfrU6+zo/w0uuoc5cKipTVwZBTLMEslKWAFi0S
            Dj7AuGk3wPXvCMSDCkMqR2EccOnfRuAR8pveRE0i1VOU6FeUviIGipN2tgG69D8M
            j2IqLU8eTCS9mTIJDTwh+K60oAbS6m9wiI47XUFdxz4lx8kayQk0UbK+bIPx4YAr
            KB+UDBhxp4gk+gmB3Hze6Z4k3xc4aVc6+YAHMZZ2YUilCa5XK4XEXh+oRkyjRaEY
            mwzM9ZC9u4oLKIX/wAFZaJq6YGSXMvqzDA8dtwrV+hEvebaU8BOPnOfxeSVOUVJ+
            27FMEKeeQ4epSn7y5+1NuAWfMe8ByzB22lcX1HipD1/Fuhj1MJ5od01U2yOehwVa
            8N8g/NufNu/XJ3745gV8L/9Jp877z5VJuEqswyKsnPu+7TrqcKHtnVChdF/3UIzS
            XAHOf0TETHzC7eODtrPd9Ao/ygEESXi+ISlwYNMcqpRMn1ppH92fV9YiY4Z6y4kX
            M5CQPFDwlsPtK6ySEe/xLvJqlKcBvLimJWcj7z8fz15rZfOuAEnVMJejAI3C
            =xlrP
            -----END PGP MESSAGE-----
          fp: DF0D30534A2926B559D22776ECE0E5FB0260172D
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
