---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: tekton
    namespace: flux-system
spec:
    interval: 5m
    chart:
        spec:
            chart: tekton-pipeline
            version: 0.24.2
            sourceRef:
                kind: HelmRepository
                name: tekton-helm-chart
                namespace: flux-system
            interval: 5m
