apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
    name: flux-system
    namespace: flux-system
spec:
    interval: 1m0s
    # Enable decryption
    decryption:
        # Use the sops provider
        provider: sops
        secretRef:
            # Reference the new 'sops-gpg' secret
            name: sops-gpg
