---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
    name: infrastructure
    namespace: flux-system
spec:
    interval: 1m0s
    path: ./infrastructure
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
    validation: client
    decryption:
        provider: sops
        secretRef:
            name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
    name: pipelines
    namespace: flux-system
spec:
    interval: 1m0s
    path: ./pipelines
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
    validation: client
    decryption:
        provider: sops
        secretRef:
            name: sops-gpg
